package org.quarkbit.controlpalabravida.dao.persistence;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.quarkbit.controlpalabravida.dao.domain.Evento;
import org.quarkbit.controlpalabravida.dao.domain.EventoExample;

public interface EventoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int countByExample(EventoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int deleteByExample(EventoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int deleteByPrimaryKey(Integer idEvento);
    
    int deleteParticipantesByPrimaryKey (Integer idEvento);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int insert(Evento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int insertSelective(Evento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    List<Evento> selectByExample(EventoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    Evento selectByPrimaryKey(Integer idEvento);
    
    List<Evento> selectByValidos();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByExampleSelective(@Param("record") Evento record, @Param("example") EventoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByExample(@Param("record") Evento record, @Param("example") EventoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByPrimaryKeySelective(Evento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByPrimaryKey(Evento record);

	void obtenerUltimoId(Map<String, Integer> mapa);
}