package org.quarkbit.controlpalabravida.dao.persistence;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.quarkbit.controlpalabravida.dao.domain.PersonaEventoAsistencia;
import org.quarkbit.controlpalabravida.dao.domain.PersonaEventoAsistenciaExample;

public interface PersonaEventoAsistenciaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int countByExample(PersonaEventoAsistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int deleteByExample(PersonaEventoAsistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int deleteByPrimaryKey(Integer idAsistencia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int insert(PersonaEventoAsistencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int insertSelective(PersonaEventoAsistencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    List<PersonaEventoAsistencia> selectByExample(PersonaEventoAsistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    PersonaEventoAsistencia selectByPrimaryKey(Integer idAsistencia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByExampleSelective(@Param("record") PersonaEventoAsistencia record, @Param("example") PersonaEventoAsistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByExample(@Param("record") PersonaEventoAsistencia record, @Param("example") PersonaEventoAsistenciaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByPrimaryKeySelective(PersonaEventoAsistencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByPrimaryKey(PersonaEventoAsistencia record);
}