package org.quarkbit.controlpalabravida.dao.persistence;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.quarkbit.controlpalabravida.dao.domain.PersonaEventoPermisos;
import org.quarkbit.controlpalabravida.dao.domain.PersonaEventoPermisosExample;

public interface PersonaEventoPermisosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_permisos
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    int countByExample(PersonaEventoPermisosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_permisos
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    int deleteByExample(PersonaEventoPermisosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_permisos
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    int deleteByPrimaryKey(Integer id_permiso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_permisos
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    int insert(PersonaEventoPermisos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_permisos
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    int insertSelective(PersonaEventoPermisos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_permisos
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    List<PersonaEventoPermisos> selectByExample(PersonaEventoPermisosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_permisos
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    PersonaEventoPermisos selectByPrimaryKey(Integer id_permiso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_permisos
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    int updateByExampleSelective(@Param("record") PersonaEventoPermisos record, @Param("example") PersonaEventoPermisosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_permisos
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    int updateByExample(@Param("record") PersonaEventoPermisos record, @Param("example") PersonaEventoPermisosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_permisos
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    int updateByPrimaryKeySelective(PersonaEventoPermisos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_eventos_permisos
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    int updateByPrimaryKey(PersonaEventoPermisos record);

	void obtenerUltimoId(Map<String, Integer> mapa);
}