package org.quarkbit.controlpalabravida.dao.persistence;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.quarkbit.controlpalabravida.dao.domain.PersonaHuellaDigital;
import org.quarkbit.controlpalabravida.dao.domain.PersonaHuellaDigitalExample;

public interface PersonaHuellaDigitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int countByExample(PersonaHuellaDigitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int deleteByExample(PersonaHuellaDigitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int deleteByPrimaryKey(Integer idHuella);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int insert(PersonaHuellaDigital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int insertSelective(PersonaHuellaDigital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    List<PersonaHuellaDigital> selectByExampleWithBLOBs(PersonaHuellaDigitalExample example);
    List<PersonaHuellaDigital> selectByValidasHuellas();
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    List<PersonaHuellaDigital> selectByExample(PersonaHuellaDigitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    PersonaHuellaDigital selectByPrimaryKey(Integer idHuella);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByExampleSelective(@Param("record") PersonaHuellaDigital record, @Param("example") PersonaHuellaDigitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByExampleWithBLOBs(@Param("record") PersonaHuellaDigital record, @Param("example") PersonaHuellaDigitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByExample(@Param("record") PersonaHuellaDigital record, @Param("example") PersonaHuellaDigitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByPrimaryKeySelective(PersonaHuellaDigital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByPrimaryKeyWithBLOBs(PersonaHuellaDigital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByPrimaryKey(PersonaHuellaDigital record);
}