package org.quarkbit.controlpalabravida.dao.persistence;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.quarkbit.controlpalabravida.dao.domain.Usuario;
import org.quarkbit.controlpalabravida.dao.domain.UsuarioExample;

public interface UsuarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int countByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int deleteByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int deleteByPrimaryKey(Integer idUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int insert(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int insertSelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    List<Usuario> selectByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    Usuario selectByPrimaryKey(Integer idUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByExampleSelective(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByExample(@Param("record") Usuario record, @Param("example") UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByPrimaryKeySelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    int updateByPrimaryKey(Usuario record);
    
    int obtenerFechaHoraServidor(Map<String, Date> mapa);

	void obtenerUltimoId(Map<String, Integer> mapa);
}