package org.quarkbit.controlpalabravida.dao.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EventoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public EventoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andIdEventoIsNull() {
            addCriterion("id_evento is null");
            return (Criteria) this;
        }

        public Criteria andIdEventoIsNotNull() {
            addCriterion("id_evento is not null");
            return (Criteria) this;
        }

        public Criteria andIdEventoEqualTo(Integer value) {
            addCriterion("id_evento =", value, "idEvento");
            return (Criteria) this;
        }

        public Criteria andIdEventoNotEqualTo(Integer value) {
            addCriterion("id_evento <>", value, "idEvento");
            return (Criteria) this;
        }

        public Criteria andIdEventoGreaterThan(Integer value) {
            addCriterion("id_evento >", value, "idEvento");
            return (Criteria) this;
        }

        public Criteria andIdEventoGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_evento >=", value, "idEvento");
            return (Criteria) this;
        }

        public Criteria andIdEventoLessThan(Integer value) {
            addCriterion("id_evento <", value, "idEvento");
            return (Criteria) this;
        }

        public Criteria andIdEventoLessThanOrEqualTo(Integer value) {
            addCriterion("id_evento <=", value, "idEvento");
            return (Criteria) this;
        }

        public Criteria andIdEventoIn(List<Integer> values) {
            addCriterion("id_evento in", values, "idEvento");
            return (Criteria) this;
        }

        public Criteria andIdEventoNotIn(List<Integer> values) {
            addCriterion("id_evento not in", values, "idEvento");
            return (Criteria) this;
        }

        public Criteria andIdEventoBetween(Integer value1, Integer value2) {
            addCriterion("id_evento between", value1, value2, "idEvento");
            return (Criteria) this;
        }

        public Criteria andIdEventoNotBetween(Integer value1, Integer value2) {
            addCriterion("id_evento not between", value1, value2, "idEvento");
            return (Criteria) this;
        }

        public Criteria andNombreEventoIsNull() {
            addCriterion("nombre_evento is null");
            return (Criteria) this;
        }

        public Criteria andNombreEventoIsNotNull() {
            addCriterion("nombre_evento is not null");
            return (Criteria) this;
        }

        public Criteria andNombreEventoEqualTo(String value) {
            addCriterion("nombre_evento =", value, "nombreEvento");
            return (Criteria) this;
        }

        public Criteria andNombreEventoNotEqualTo(String value) {
            addCriterion("nombre_evento <>", value, "nombreEvento");
            return (Criteria) this;
        }

        public Criteria andNombreEventoGreaterThan(String value) {
            addCriterion("nombre_evento >", value, "nombreEvento");
            return (Criteria) this;
        }

        public Criteria andNombreEventoGreaterThanOrEqualTo(String value) {
            addCriterion("nombre_evento >=", value, "nombreEvento");
            return (Criteria) this;
        }

        public Criteria andNombreEventoLessThan(String value) {
            addCriterion("nombre_evento <", value, "nombreEvento");
            return (Criteria) this;
        }

        public Criteria andNombreEventoLessThanOrEqualTo(String value) {
            addCriterion("nombre_evento <=", value, "nombreEvento");
            return (Criteria) this;
        }

        public Criteria andNombreEventoLike(String value) {
            addCriterion("nombre_evento like", value, "nombreEvento");
            return (Criteria) this;
        }

        public Criteria andNombreEventoNotLike(String value) {
            addCriterion("nombre_evento not like", value, "nombreEvento");
            return (Criteria) this;
        }

        public Criteria andNombreEventoIn(List<String> values) {
            addCriterion("nombre_evento in", values, "nombreEvento");
            return (Criteria) this;
        }

        public Criteria andNombreEventoNotIn(List<String> values) {
            addCriterion("nombre_evento not in", values, "nombreEvento");
            return (Criteria) this;
        }

        public Criteria andNombreEventoBetween(String value1, String value2) {
            addCriterion("nombre_evento between", value1, value2, "nombreEvento");
            return (Criteria) this;
        }

        public Criteria andNombreEventoNotBetween(String value1, String value2) {
            addCriterion("nombre_evento not between", value1, value2, "nombreEvento");
            return (Criteria) this;
        }

        public Criteria andGestionIsNull() {
            addCriterion("gestion is null");
            return (Criteria) this;
        }

        public Criteria andGestionIsNotNull() {
            addCriterion("gestion is not null");
            return (Criteria) this;
        }

        public Criteria andGestionEqualTo(Integer value) {
            addCriterion("gestion =", value, "gestion");
            return (Criteria) this;
        }

        public Criteria andGestionNotEqualTo(Integer value) {
            addCriterion("gestion <>", value, "gestion");
            return (Criteria) this;
        }

        public Criteria andGestionGreaterThan(Integer value) {
            addCriterion("gestion >", value, "gestion");
            return (Criteria) this;
        }

        public Criteria andGestionGreaterThanOrEqualTo(Integer value) {
            addCriterion("gestion >=", value, "gestion");
            return (Criteria) this;
        }

        public Criteria andGestionLessThan(Integer value) {
            addCriterion("gestion <", value, "gestion");
            return (Criteria) this;
        }

        public Criteria andGestionLessThanOrEqualTo(Integer value) {
            addCriterion("gestion <=", value, "gestion");
            return (Criteria) this;
        }

        public Criteria andGestionIn(List<Integer> values) {
            addCriterion("gestion in", values, "gestion");
            return (Criteria) this;
        }

        public Criteria andGestionNotIn(List<Integer> values) {
            addCriterion("gestion not in", values, "gestion");
            return (Criteria) this;
        }

        public Criteria andGestionBetween(Integer value1, Integer value2) {
            addCriterion("gestion between", value1, value2, "gestion");
            return (Criteria) this;
        }

        public Criteria andGestionNotBetween(Integer value1, Integer value2) {
            addCriterion("gestion not between", value1, value2, "gestion");
            return (Criteria) this;
        }

        public Criteria andCodigoEstadoIsNull() {
            addCriterion("codigo_estado is null");
            return (Criteria) this;
        }

        public Criteria andCodigoEstadoIsNotNull() {
            addCriterion("codigo_estado is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoEstadoEqualTo(String value) {
            addCriterion("codigo_estado =", value, "codigoEstado");
            return (Criteria) this;
        }

        public Criteria andCodigoEstadoNotEqualTo(String value) {
            addCriterion("codigo_estado <>", value, "codigoEstado");
            return (Criteria) this;
        }

        public Criteria andCodigoEstadoGreaterThan(String value) {
            addCriterion("codigo_estado >", value, "codigoEstado");
            return (Criteria) this;
        }

        public Criteria andCodigoEstadoGreaterThanOrEqualTo(String value) {
            addCriterion("codigo_estado >=", value, "codigoEstado");
            return (Criteria) this;
        }

        public Criteria andCodigoEstadoLessThan(String value) {
            addCriterion("codigo_estado <", value, "codigoEstado");
            return (Criteria) this;
        }

        public Criteria andCodigoEstadoLessThanOrEqualTo(String value) {
            addCriterion("codigo_estado <=", value, "codigoEstado");
            return (Criteria) this;
        }

        public Criteria andCodigoEstadoLike(String value) {
            addCriterion("codigo_estado like", value, "codigoEstado");
            return (Criteria) this;
        }

        public Criteria andCodigoEstadoNotLike(String value) {
            addCriterion("codigo_estado not like", value, "codigoEstado");
            return (Criteria) this;
        }

        public Criteria andCodigoEstadoIn(List<String> values) {
            addCriterion("codigo_estado in", values, "codigoEstado");
            return (Criteria) this;
        }

        public Criteria andCodigoEstadoNotIn(List<String> values) {
            addCriterion("codigo_estado not in", values, "codigoEstado");
            return (Criteria) this;
        }

        public Criteria andCodigoEstadoBetween(String value1, String value2) {
            addCriterion("codigo_estado between", value1, value2, "codigoEstado");
            return (Criteria) this;
        }

        public Criteria andCodigoEstadoNotBetween(String value1, String value2) {
            addCriterion("codigo_estado not between", value1, value2, "codigoEstado");
            return (Criteria) this;
        }

        public Criteria andControlLunesIsNull() {
            addCriterion("control_lunes is null");
            return (Criteria) this;
        }

        public Criteria andControlLunesIsNotNull() {
            addCriterion("control_lunes is not null");
            return (Criteria) this;
        }

        public Criteria andControlLunesEqualTo(Boolean value) {
            addCriterion("control_lunes =", value, "controlLunes");
            return (Criteria) this;
        }

        public Criteria andControlLunesNotEqualTo(Boolean value) {
            addCriterion("control_lunes <>", value, "controlLunes");
            return (Criteria) this;
        }

        public Criteria andControlLunesGreaterThan(Boolean value) {
            addCriterion("control_lunes >", value, "controlLunes");
            return (Criteria) this;
        }

        public Criteria andControlLunesGreaterThanOrEqualTo(Boolean value) {
            addCriterion("control_lunes >=", value, "controlLunes");
            return (Criteria) this;
        }

        public Criteria andControlLunesLessThan(Boolean value) {
            addCriterion("control_lunes <", value, "controlLunes");
            return (Criteria) this;
        }

        public Criteria andControlLunesLessThanOrEqualTo(Boolean value) {
            addCriterion("control_lunes <=", value, "controlLunes");
            return (Criteria) this;
        }

        public Criteria andControlLunesIn(List<Boolean> values) {
            addCriterion("control_lunes in", values, "controlLunes");
            return (Criteria) this;
        }

        public Criteria andControlLunesNotIn(List<Boolean> values) {
            addCriterion("control_lunes not in", values, "controlLunes");
            return (Criteria) this;
        }

        public Criteria andControlLunesBetween(Boolean value1, Boolean value2) {
            addCriterion("control_lunes between", value1, value2, "controlLunes");
            return (Criteria) this;
        }

        public Criteria andControlLunesNotBetween(Boolean value1, Boolean value2) {
            addCriterion("control_lunes not between", value1, value2, "controlLunes");
            return (Criteria) this;
        }

        public Criteria andControlMartesIsNull() {
            addCriterion("control_martes is null");
            return (Criteria) this;
        }

        public Criteria andControlMartesIsNotNull() {
            addCriterion("control_martes is not null");
            return (Criteria) this;
        }

        public Criteria andControlMartesEqualTo(Boolean value) {
            addCriterion("control_martes =", value, "controlMartes");
            return (Criteria) this;
        }

        public Criteria andControlMartesNotEqualTo(Boolean value) {
            addCriterion("control_martes <>", value, "controlMartes");
            return (Criteria) this;
        }

        public Criteria andControlMartesGreaterThan(Boolean value) {
            addCriterion("control_martes >", value, "controlMartes");
            return (Criteria) this;
        }

        public Criteria andControlMartesGreaterThanOrEqualTo(Boolean value) {
            addCriterion("control_martes >=", value, "controlMartes");
            return (Criteria) this;
        }

        public Criteria andControlMartesLessThan(Boolean value) {
            addCriterion("control_martes <", value, "controlMartes");
            return (Criteria) this;
        }

        public Criteria andControlMartesLessThanOrEqualTo(Boolean value) {
            addCriterion("control_martes <=", value, "controlMartes");
            return (Criteria) this;
        }

        public Criteria andControlMartesIn(List<Boolean> values) {
            addCriterion("control_martes in", values, "controlMartes");
            return (Criteria) this;
        }

        public Criteria andControlMartesNotIn(List<Boolean> values) {
            addCriterion("control_martes not in", values, "controlMartes");
            return (Criteria) this;
        }

        public Criteria andControlMartesBetween(Boolean value1, Boolean value2) {
            addCriterion("control_martes between", value1, value2, "controlMartes");
            return (Criteria) this;
        }

        public Criteria andControlMartesNotBetween(Boolean value1, Boolean value2) {
            addCriterion("control_martes not between", value1, value2, "controlMartes");
            return (Criteria) this;
        }

        public Criteria andControlMiercolesIsNull() {
            addCriterion("control_miercoles is null");
            return (Criteria) this;
        }

        public Criteria andControlMiercolesIsNotNull() {
            addCriterion("control_miercoles is not null");
            return (Criteria) this;
        }

        public Criteria andControlMiercolesEqualTo(Boolean value) {
            addCriterion("control_miercoles =", value, "controlMiercoles");
            return (Criteria) this;
        }

        public Criteria andControlMiercolesNotEqualTo(Boolean value) {
            addCriterion("control_miercoles <>", value, "controlMiercoles");
            return (Criteria) this;
        }

        public Criteria andControlMiercolesGreaterThan(Boolean value) {
            addCriterion("control_miercoles >", value, "controlMiercoles");
            return (Criteria) this;
        }

        public Criteria andControlMiercolesGreaterThanOrEqualTo(Boolean value) {
            addCriterion("control_miercoles >=", value, "controlMiercoles");
            return (Criteria) this;
        }

        public Criteria andControlMiercolesLessThan(Boolean value) {
            addCriterion("control_miercoles <", value, "controlMiercoles");
            return (Criteria) this;
        }

        public Criteria andControlMiercolesLessThanOrEqualTo(Boolean value) {
            addCriterion("control_miercoles <=", value, "controlMiercoles");
            return (Criteria) this;
        }

        public Criteria andControlMiercolesIn(List<Boolean> values) {
            addCriterion("control_miercoles in", values, "controlMiercoles");
            return (Criteria) this;
        }

        public Criteria andControlMiercolesNotIn(List<Boolean> values) {
            addCriterion("control_miercoles not in", values, "controlMiercoles");
            return (Criteria) this;
        }

        public Criteria andControlMiercolesBetween(Boolean value1, Boolean value2) {
            addCriterion("control_miercoles between", value1, value2, "controlMiercoles");
            return (Criteria) this;
        }

        public Criteria andControlMiercolesNotBetween(Boolean value1, Boolean value2) {
            addCriterion("control_miercoles not between", value1, value2, "controlMiercoles");
            return (Criteria) this;
        }

        public Criteria andControlJuevesIsNull() {
            addCriterion("control_jueves is null");
            return (Criteria) this;
        }

        public Criteria andControlJuevesIsNotNull() {
            addCriterion("control_jueves is not null");
            return (Criteria) this;
        }

        public Criteria andControlJuevesEqualTo(Boolean value) {
            addCriterion("control_jueves =", value, "controlJueves");
            return (Criteria) this;
        }

        public Criteria andControlJuevesNotEqualTo(Boolean value) {
            addCriterion("control_jueves <>", value, "controlJueves");
            return (Criteria) this;
        }

        public Criteria andControlJuevesGreaterThan(Boolean value) {
            addCriterion("control_jueves >", value, "controlJueves");
            return (Criteria) this;
        }

        public Criteria andControlJuevesGreaterThanOrEqualTo(Boolean value) {
            addCriterion("control_jueves >=", value, "controlJueves");
            return (Criteria) this;
        }

        public Criteria andControlJuevesLessThan(Boolean value) {
            addCriterion("control_jueves <", value, "controlJueves");
            return (Criteria) this;
        }

        public Criteria andControlJuevesLessThanOrEqualTo(Boolean value) {
            addCriterion("control_jueves <=", value, "controlJueves");
            return (Criteria) this;
        }

        public Criteria andControlJuevesIn(List<Boolean> values) {
            addCriterion("control_jueves in", values, "controlJueves");
            return (Criteria) this;
        }

        public Criteria andControlJuevesNotIn(List<Boolean> values) {
            addCriterion("control_jueves not in", values, "controlJueves");
            return (Criteria) this;
        }

        public Criteria andControlJuevesBetween(Boolean value1, Boolean value2) {
            addCriterion("control_jueves between", value1, value2, "controlJueves");
            return (Criteria) this;
        }

        public Criteria andControlJuevesNotBetween(Boolean value1, Boolean value2) {
            addCriterion("control_jueves not between", value1, value2, "controlJueves");
            return (Criteria) this;
        }

        public Criteria andControlViernesIsNull() {
            addCriterion("control_viernes is null");
            return (Criteria) this;
        }

        public Criteria andControlViernesIsNotNull() {
            addCriterion("control_viernes is not null");
            return (Criteria) this;
        }

        public Criteria andControlViernesEqualTo(Boolean value) {
            addCriterion("control_viernes =", value, "controlViernes");
            return (Criteria) this;
        }

        public Criteria andControlViernesNotEqualTo(Boolean value) {
            addCriterion("control_viernes <>", value, "controlViernes");
            return (Criteria) this;
        }

        public Criteria andControlViernesGreaterThan(Boolean value) {
            addCriterion("control_viernes >", value, "controlViernes");
            return (Criteria) this;
        }

        public Criteria andControlViernesGreaterThanOrEqualTo(Boolean value) {
            addCriterion("control_viernes >=", value, "controlViernes");
            return (Criteria) this;
        }

        public Criteria andControlViernesLessThan(Boolean value) {
            addCriterion("control_viernes <", value, "controlViernes");
            return (Criteria) this;
        }

        public Criteria andControlViernesLessThanOrEqualTo(Boolean value) {
            addCriterion("control_viernes <=", value, "controlViernes");
            return (Criteria) this;
        }

        public Criteria andControlViernesIn(List<Boolean> values) {
            addCriterion("control_viernes in", values, "controlViernes");
            return (Criteria) this;
        }

        public Criteria andControlViernesNotIn(List<Boolean> values) {
            addCriterion("control_viernes not in", values, "controlViernes");
            return (Criteria) this;
        }

        public Criteria andControlViernesBetween(Boolean value1, Boolean value2) {
            addCriterion("control_viernes between", value1, value2, "controlViernes");
            return (Criteria) this;
        }

        public Criteria andControlViernesNotBetween(Boolean value1, Boolean value2) {
            addCriterion("control_viernes not between", value1, value2, "controlViernes");
            return (Criteria) this;
        }

        public Criteria andControlSabadoIsNull() {
            addCriterion("control_sabado is null");
            return (Criteria) this;
        }

        public Criteria andControlSabadoIsNotNull() {
            addCriterion("control_sabado is not null");
            return (Criteria) this;
        }

        public Criteria andControlSabadoEqualTo(Boolean value) {
            addCriterion("control_sabado =", value, "controlSabado");
            return (Criteria) this;
        }

        public Criteria andControlSabadoNotEqualTo(Boolean value) {
            addCriterion("control_sabado <>", value, "controlSabado");
            return (Criteria) this;
        }

        public Criteria andControlSabadoGreaterThan(Boolean value) {
            addCriterion("control_sabado >", value, "controlSabado");
            return (Criteria) this;
        }

        public Criteria andControlSabadoGreaterThanOrEqualTo(Boolean value) {
            addCriterion("control_sabado >=", value, "controlSabado");
            return (Criteria) this;
        }

        public Criteria andControlSabadoLessThan(Boolean value) {
            addCriterion("control_sabado <", value, "controlSabado");
            return (Criteria) this;
        }

        public Criteria andControlSabadoLessThanOrEqualTo(Boolean value) {
            addCriterion("control_sabado <=", value, "controlSabado");
            return (Criteria) this;
        }

        public Criteria andControlSabadoIn(List<Boolean> values) {
            addCriterion("control_sabado in", values, "controlSabado");
            return (Criteria) this;
        }

        public Criteria andControlSabadoNotIn(List<Boolean> values) {
            addCriterion("control_sabado not in", values, "controlSabado");
            return (Criteria) this;
        }

        public Criteria andControlSabadoBetween(Boolean value1, Boolean value2) {
            addCriterion("control_sabado between", value1, value2, "controlSabado");
            return (Criteria) this;
        }

        public Criteria andControlSabadoNotBetween(Boolean value1, Boolean value2) {
            addCriterion("control_sabado not between", value1, value2, "controlSabado");
            return (Criteria) this;
        }

        public Criteria andControlDomingoIsNull() {
            addCriterion("control_domingo is null");
            return (Criteria) this;
        }

        public Criteria andControlDomingoIsNotNull() {
            addCriterion("control_domingo is not null");
            return (Criteria) this;
        }

        public Criteria andControlDomingoEqualTo(Boolean value) {
            addCriterion("control_domingo =", value, "controlDomingo");
            return (Criteria) this;
        }

        public Criteria andControlDomingoNotEqualTo(Boolean value) {
            addCriterion("control_domingo <>", value, "controlDomingo");
            return (Criteria) this;
        }

        public Criteria andControlDomingoGreaterThan(Boolean value) {
            addCriterion("control_domingo >", value, "controlDomingo");
            return (Criteria) this;
        }

        public Criteria andControlDomingoGreaterThanOrEqualTo(Boolean value) {
            addCriterion("control_domingo >=", value, "controlDomingo");
            return (Criteria) this;
        }

        public Criteria andControlDomingoLessThan(Boolean value) {
            addCriterion("control_domingo <", value, "controlDomingo");
            return (Criteria) this;
        }

        public Criteria andControlDomingoLessThanOrEqualTo(Boolean value) {
            addCriterion("control_domingo <=", value, "controlDomingo");
            return (Criteria) this;
        }

        public Criteria andControlDomingoIn(List<Boolean> values) {
            addCriterion("control_domingo in", values, "controlDomingo");
            return (Criteria) this;
        }

        public Criteria andControlDomingoNotIn(List<Boolean> values) {
            addCriterion("control_domingo not in", values, "controlDomingo");
            return (Criteria) this;
        }

        public Criteria andControlDomingoBetween(Boolean value1, Boolean value2) {
            addCriterion("control_domingo between", value1, value2, "controlDomingo");
            return (Criteria) this;
        }

        public Criteria andControlDomingoNotBetween(Boolean value1, Boolean value2) {
            addCriterion("control_domingo not between", value1, value2, "controlDomingo");
            return (Criteria) this;
        }

        public Criteria andHoraInicioIsNull() {
            addCriterion("hora_inicio is null");
            return (Criteria) this;
        }

        public Criteria andHoraInicioIsNotNull() {
            addCriterion("hora_inicio is not null");
            return (Criteria) this;
        }

        public Criteria andHoraInicioEqualTo(Date value) {
            addCriterionForJDBCTime("hora_inicio =", value, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioNotEqualTo(Date value) {
            addCriterionForJDBCTime("hora_inicio <>", value, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioGreaterThan(Date value) {
            addCriterionForJDBCTime("hora_inicio >", value, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("hora_inicio >=", value, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioLessThan(Date value) {
            addCriterionForJDBCTime("hora_inicio <", value, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("hora_inicio <=", value, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioIn(List<Date> values) {
            addCriterionForJDBCTime("hora_inicio in", values, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioNotIn(List<Date> values) {
            addCriterionForJDBCTime("hora_inicio not in", values, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("hora_inicio between", value1, value2, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraInicioNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("hora_inicio not between", value1, value2, "horaInicio");
            return (Criteria) this;
        }

        public Criteria andHoraFinIsNull() {
            addCriterion("hora_fin is null");
            return (Criteria) this;
        }

        public Criteria andHoraFinIsNotNull() {
            addCriterion("hora_fin is not null");
            return (Criteria) this;
        }

        public Criteria andHoraFinEqualTo(Date value) {
            addCriterionForJDBCTime("hora_fin =", value, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinNotEqualTo(Date value) {
            addCriterionForJDBCTime("hora_fin <>", value, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinGreaterThan(Date value) {
            addCriterionForJDBCTime("hora_fin >", value, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("hora_fin >=", value, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinLessThan(Date value) {
            addCriterionForJDBCTime("hora_fin <", value, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("hora_fin <=", value, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinIn(List<Date> values) {
            addCriterionForJDBCTime("hora_fin in", values, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinNotIn(List<Date> values) {
            addCriterionForJDBCTime("hora_fin not in", values, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("hora_fin between", value1, value2, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraFinNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("hora_fin not between", value1, value2, "horaFin");
            return (Criteria) this;
        }

        public Criteria andHoraInicioAntesIsNull() {
            addCriterion("hora_inicio_antes is null");
            return (Criteria) this;
        }

        public Criteria andHoraInicioAntesIsNotNull() {
            addCriterion("hora_inicio_antes is not null");
            return (Criteria) this;
        }

        public Criteria andHoraInicioAntesEqualTo(Date value) {
            addCriterionForJDBCTime("hora_inicio_antes =", value, "horaInicioAntes");
            return (Criteria) this;
        }

        public Criteria andHoraInicioAntesNotEqualTo(Date value) {
            addCriterionForJDBCTime("hora_inicio_antes <>", value, "horaInicioAntes");
            return (Criteria) this;
        }

        public Criteria andHoraInicioAntesGreaterThan(Date value) {
            addCriterionForJDBCTime("hora_inicio_antes >", value, "horaInicioAntes");
            return (Criteria) this;
        }

        public Criteria andHoraInicioAntesGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("hora_inicio_antes >=", value, "horaInicioAntes");
            return (Criteria) this;
        }

        public Criteria andHoraInicioAntesLessThan(Date value) {
            addCriterionForJDBCTime("hora_inicio_antes <", value, "horaInicioAntes");
            return (Criteria) this;
        }

        public Criteria andHoraInicioAntesLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("hora_inicio_antes <=", value, "horaInicioAntes");
            return (Criteria) this;
        }

        public Criteria andHoraInicioAntesIn(List<Date> values) {
            addCriterionForJDBCTime("hora_inicio_antes in", values, "horaInicioAntes");
            return (Criteria) this;
        }

        public Criteria andHoraInicioAntesNotIn(List<Date> values) {
            addCriterionForJDBCTime("hora_inicio_antes not in", values, "horaInicioAntes");
            return (Criteria) this;
        }

        public Criteria andHoraInicioAntesBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("hora_inicio_antes between", value1, value2, "horaInicioAntes");
            return (Criteria) this;
        }

        public Criteria andHoraInicioAntesNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("hora_inicio_antes not between", value1, value2, "horaInicioAntes");
            return (Criteria) this;
        }

        public Criteria andHoraFinRetrasoIsNull() {
            addCriterion("hora_fin_retraso is null");
            return (Criteria) this;
        }

        public Criteria andHoraFinRetrasoIsNotNull() {
            addCriterion("hora_fin_retraso is not null");
            return (Criteria) this;
        }

        public Criteria andHoraFinRetrasoEqualTo(Date value) {
            addCriterionForJDBCTime("hora_fin_retraso =", value, "horaFinRetraso");
            return (Criteria) this;
        }

        public Criteria andHoraFinRetrasoNotEqualTo(Date value) {
            addCriterionForJDBCTime("hora_fin_retraso <>", value, "horaFinRetraso");
            return (Criteria) this;
        }

        public Criteria andHoraFinRetrasoGreaterThan(Date value) {
            addCriterionForJDBCTime("hora_fin_retraso >", value, "horaFinRetraso");
            return (Criteria) this;
        }

        public Criteria andHoraFinRetrasoGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("hora_fin_retraso >=", value, "horaFinRetraso");
            return (Criteria) this;
        }

        public Criteria andHoraFinRetrasoLessThan(Date value) {
            addCriterionForJDBCTime("hora_fin_retraso <", value, "horaFinRetraso");
            return (Criteria) this;
        }

        public Criteria andHoraFinRetrasoLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("hora_fin_retraso <=", value, "horaFinRetraso");
            return (Criteria) this;
        }

        public Criteria andHoraFinRetrasoIn(List<Date> values) {
            addCriterionForJDBCTime("hora_fin_retraso in", values, "horaFinRetraso");
            return (Criteria) this;
        }

        public Criteria andHoraFinRetrasoNotIn(List<Date> values) {
            addCriterionForJDBCTime("hora_fin_retraso not in", values, "horaFinRetraso");
            return (Criteria) this;
        }

        public Criteria andHoraFinRetrasoBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("hora_fin_retraso between", value1, value2, "horaFinRetraso");
            return (Criteria) this;
        }

        public Criteria andHoraFinRetrasoNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("hora_fin_retraso not between", value1, value2, "horaFinRetraso");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("descripcion is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("descripcion is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("descripcion =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("descripcion <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("descripcion >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("descripcion >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("descripcion <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("descripcion <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("descripcion like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("descripcion not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("descripcion in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("descripcion not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("descripcion between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("descripcion not between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andFechaInicioIsNull() {
            addCriterion("fecha_inicio is null");
            return (Criteria) this;
        }

        public Criteria andFechaInicioIsNotNull() {
            addCriterion("fecha_inicio is not null");
            return (Criteria) this;
        }

        public Criteria andFechaInicioEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_inicio =", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_inicio <>", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha_inicio >", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_inicio >=", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioLessThan(Date value) {
            addCriterionForJDBCDate("fecha_inicio <", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_inicio <=", value, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_inicio in", values, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_inicio not in", values, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_inicio between", value1, value2, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaInicioNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_inicio not between", value1, value2, "fechaInicio");
            return (Criteria) this;
        }

        public Criteria andFechaFinIsNull() {
            addCriterion("fecha_fin is null");
            return (Criteria) this;
        }

        public Criteria andFechaFinIsNotNull() {
            addCriterion("fecha_fin is not null");
            return (Criteria) this;
        }

        public Criteria andFechaFinEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_fin =", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_fin <>", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha_fin >", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_fin >=", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinLessThan(Date value) {
            addCriterionForJDBCDate("fecha_fin <", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_fin <=", value, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_fin in", values, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_fin not in", values, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_fin between", value1, value2, "fechaFin");
            return (Criteria) this;
        }

        public Criteria andFechaFinNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_fin not between", value1, value2, "fechaFin");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eventos
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 03 02:37:34 BOT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eventos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}