package org.quarkbit.controlpalabravida.dao.domain;

public class EventoPersonaKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos_personas.id_evento
     *
     * @mbggenerated Mon Jun 06 22:34:46 BOT 2016
     */
    private Integer idEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos_personas.id_persona
     *
     * @mbggenerated Mon Jun 06 22:34:46 BOT 2016
     */
    private Integer idPersona;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos_personas.id_evento
     *
     * @return the value of eventos_personas.id_evento
     *
     * @mbggenerated Mon Jun 06 22:34:46 BOT 2016
     */
    public Integer getIdEvento() {
        return idEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos_personas.id_evento
     *
     * @param idEvento the value for eventos_personas.id_evento
     *
     * @mbggenerated Mon Jun 06 22:34:46 BOT 2016
     */
    public void setIdEvento(Integer idEvento) {
        this.idEvento = idEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos_personas.id_persona
     *
     * @return the value of eventos_personas.id_persona
     *
     * @mbggenerated Mon Jun 06 22:34:46 BOT 2016
     */
    public Integer getIdPersona() {
        return idPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos_personas.id_persona
     *
     * @param idPersona the value for eventos_personas.id_persona
     *
     * @mbggenerated Mon Jun 06 22:34:46 BOT 2016
     */
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
}