package org.quarkbit.controlpalabravida.dao.domain;

import java.util.Date;

public class EventoPersona extends EventoPersonaKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos_personas.fecha_inicio
     *
     * @mbggenerated Mon Jun 06 22:34:46 BOT 2016
     */
    private Date fechaInicio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos_personas.fecha_fin
     *
     * @mbggenerated Mon Jun 06 22:34:46 BOT 2016
     */
    private Date fechaFin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos_personas.fecha_inicio
     *
     * @return the value of eventos_personas.fecha_inicio
     *
     * @mbggenerated Mon Jun 06 22:34:46 BOT 2016
     */
    public Date getFechaInicio() {
        return fechaInicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos_personas.fecha_inicio
     *
     * @param fechaInicio the value for eventos_personas.fecha_inicio
     *
     * @mbggenerated Mon Jun 06 22:34:46 BOT 2016
     */
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos_personas.fecha_fin
     *
     * @return the value of eventos_personas.fecha_fin
     *
     * @mbggenerated Mon Jun 06 22:34:46 BOT 2016
     */
    public Date getFechaFin() {
        return fechaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos_personas.fecha_fin
     *
     * @param fechaFin the value for eventos_personas.fecha_fin
     *
     * @mbggenerated Mon Jun 06 22:34:46 BOT 2016
     */
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
}