package org.quarkbit.controlpalabravida.dao.domain;

import java.util.Date;

public class Evento implements Comparable<Evento> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.id_evento
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Integer idEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.nombre_evento
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String nombreEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.gestion
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Integer gestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.codigo_estado
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String codigoEstado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.control_lunes
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Boolean controlLunes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.control_martes
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Boolean controlMartes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.control_miercoles
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Boolean controlMiercoles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.control_jueves
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Boolean controlJueves;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.control_viernes
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Boolean controlViernes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.control_sabado
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Boolean controlSabado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.control_domingo
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Boolean controlDomingo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.hora_inicio
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Date horaInicio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.hora_fin
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Date horaFin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.hora_inicio_antes
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Date horaInicioAntes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.hora_fin_retraso
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Date horaFinRetraso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.descripcion
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String descripcion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.fecha_inicio
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Date fechaInicio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventos.fecha_fin
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Date fechaFin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.id_evento
     *
     * @return the value of eventos.id_evento
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Integer getIdEvento() {
        return idEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.id_evento
     *
     * @param idEvento the value for eventos.id_evento
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setIdEvento(Integer idEvento) {
        this.idEvento = idEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.nombre_evento
     *
     * @return the value of eventos.nombre_evento
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getNombreEvento() {
        return nombreEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.nombre_evento
     *
     * @param nombreEvento the value for eventos.nombre_evento
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setNombreEvento(String nombreEvento) {
        this.nombreEvento = nombreEvento == null ? null : nombreEvento.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.gestion
     *
     * @return the value of eventos.gestion
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Integer getGestion() {
        return gestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.gestion
     *
     * @param gestion the value for eventos.gestion
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setGestion(Integer gestion) {
        this.gestion = gestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.codigo_estado
     *
     * @return the value of eventos.codigo_estado
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getCodigoEstado() {
        return codigoEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.codigo_estado
     *
     * @param codigoEstado the value for eventos.codigo_estado
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setCodigoEstado(String codigoEstado) {
        this.codigoEstado = codigoEstado == null ? null : codigoEstado.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.control_lunes
     *
     * @return the value of eventos.control_lunes
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Boolean getControlLunes() {
        return controlLunes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.control_lunes
     *
     * @param controlLunes the value for eventos.control_lunes
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setControlLunes(Boolean controlLunes) {
        this.controlLunes = controlLunes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.control_martes
     *
     * @return the value of eventos.control_martes
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Boolean getControlMartes() {
        return controlMartes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.control_martes
     *
     * @param controlMartes the value for eventos.control_martes
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setControlMartes(Boolean controlMartes) {
        this.controlMartes = controlMartes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.control_miercoles
     *
     * @return the value of eventos.control_miercoles
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Boolean getControlMiercoles() {
        return controlMiercoles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.control_miercoles
     *
     * @param controlMiercoles the value for eventos.control_miercoles
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setControlMiercoles(Boolean controlMiercoles) {
        this.controlMiercoles = controlMiercoles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.control_jueves
     *
     * @return the value of eventos.control_jueves
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Boolean getControlJueves() {
        return controlJueves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.control_jueves
     *
     * @param controlJueves the value for eventos.control_jueves
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setControlJueves(Boolean controlJueves) {
        this.controlJueves = controlJueves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.control_viernes
     *
     * @return the value of eventos.control_viernes
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Boolean getControlViernes() {
        return controlViernes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.control_viernes
     *
     * @param controlViernes the value for eventos.control_viernes
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setControlViernes(Boolean controlViernes) {
        this.controlViernes = controlViernes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.control_sabado
     *
     * @return the value of eventos.control_sabado
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Boolean getControlSabado() {
        return controlSabado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.control_sabado
     *
     * @param controlSabado the value for eventos.control_sabado
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setControlSabado(Boolean controlSabado) {
        this.controlSabado = controlSabado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.control_domingo
     *
     * @return the value of eventos.control_domingo
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Boolean getControlDomingo() {
        return controlDomingo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.control_domingo
     *
     * @param controlDomingo the value for eventos.control_domingo
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setControlDomingo(Boolean controlDomingo) {
        this.controlDomingo = controlDomingo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.hora_inicio
     *
     * @return the value of eventos.hora_inicio
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Date getHoraInicio() {
        return horaInicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.hora_inicio
     *
     * @param horaInicio the value for eventos.hora_inicio
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.hora_fin
     *
     * @return the value of eventos.hora_fin
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Date getHoraFin() {
        return horaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.hora_fin
     *
     * @param horaFin the value for eventos.hora_fin
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.hora_inicio_antes
     *
     * @return the value of eventos.hora_inicio_antes
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Date getHoraInicioAntes() {
        return horaInicioAntes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.hora_inicio_antes
     *
     * @param horaInicioAntes the value for eventos.hora_inicio_antes
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setHoraInicioAntes(Date horaInicioAntes) {
        this.horaInicioAntes = horaInicioAntes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.hora_fin_retraso
     *
     * @return the value of eventos.hora_fin_retraso
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Date getHoraFinRetraso() {
        return horaFinRetraso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.hora_fin_retraso
     *
     * @param horaFinRetraso the value for eventos.hora_fin_retraso
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setHoraFinRetraso(Date horaFinRetraso) {
        this.horaFinRetraso = horaFinRetraso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.descripcion
     *
     * @return the value of eventos.descripcion
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.descripcion
     *
     * @param descripcion the value for eventos.descripcion
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.fecha_inicio
     *
     * @return the value of eventos.fecha_inicio
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Date getFechaInicio() {
        return fechaInicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.fecha_inicio
     *
     * @param fechaInicio the value for eventos.fecha_inicio
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventos.fecha_fin
     *
     * @return the value of eventos.fecha_fin
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Date getFechaFin() {
        return fechaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventos.fecha_fin
     *
     * @param fechaFin the value for eventos.fecha_fin
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

	@Override
	public int compareTo(Evento o) {
		// TODO Auto-generated method stub
		return o.nombreEvento.compareTo(nombreEvento);
	}

	public String obtenerEstado() {
		// TODO Auto-generated method stub
		switch (codigoEstado.charAt(0)) {
		case 'A':
			return "HABILITADO";
		case 'B':
			return "BAJA";			
		case 'S':
			return "SUSPENDIDO";
		default:
			break;
		}
		return null;
	}
	
	public void enviarEstado(String estado) {
		// TODO Auto-generated method stub
		if(estado.compareTo("HABILITADO") == 0)
			this.codigoEstado = "A";
		if(estado.compareTo("BAJA") == 0)
			this.codigoEstado = "B";
		if(estado.compareTo("SUSPENDIDO") == 0)
			this.codigoEstado = "S";
	}
}