package org.quarkbit.controlpalabravida.dao.domain;

import java.util.ArrayList;
import java.util.List;

public class PersonaHuellaDigitalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public PersonaHuellaDigitalExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdHuellaIsNull() {
            addCriterion("id_huella is null");
            return (Criteria) this;
        }

        public Criteria andIdHuellaIsNotNull() {
            addCriterion("id_huella is not null");
            return (Criteria) this;
        }

        public Criteria andIdHuellaEqualTo(Integer value) {
            addCriterion("id_huella =", value, "idHuella");
            return (Criteria) this;
        }

        public Criteria andIdHuellaNotEqualTo(Integer value) {
            addCriterion("id_huella <>", value, "idHuella");
            return (Criteria) this;
        }

        public Criteria andIdHuellaGreaterThan(Integer value) {
            addCriterion("id_huella >", value, "idHuella");
            return (Criteria) this;
        }

        public Criteria andIdHuellaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_huella >=", value, "idHuella");
            return (Criteria) this;
        }

        public Criteria andIdHuellaLessThan(Integer value) {
            addCriterion("id_huella <", value, "idHuella");
            return (Criteria) this;
        }

        public Criteria andIdHuellaLessThanOrEqualTo(Integer value) {
            addCriterion("id_huella <=", value, "idHuella");
            return (Criteria) this;
        }

        public Criteria andIdHuellaIn(List<Integer> values) {
            addCriterion("id_huella in", values, "idHuella");
            return (Criteria) this;
        }

        public Criteria andIdHuellaNotIn(List<Integer> values) {
            addCriterion("id_huella not in", values, "idHuella");
            return (Criteria) this;
        }

        public Criteria andIdHuellaBetween(Integer value1, Integer value2) {
            addCriterion("id_huella between", value1, value2, "idHuella");
            return (Criteria) this;
        }

        public Criteria andIdHuellaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_huella not between", value1, value2, "idHuella");
            return (Criteria) this;
        }

        public Criteria andIdPersonaIsNull() {
            addCriterion("id_persona is null");
            return (Criteria) this;
        }

        public Criteria andIdPersonaIsNotNull() {
            addCriterion("id_persona is not null");
            return (Criteria) this;
        }

        public Criteria andIdPersonaEqualTo(Integer value) {
            addCriterion("id_persona =", value, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaNotEqualTo(Integer value) {
            addCriterion("id_persona <>", value, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaGreaterThan(Integer value) {
            addCriterion("id_persona >", value, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_persona >=", value, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaLessThan(Integer value) {
            addCriterion("id_persona <", value, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaLessThanOrEqualTo(Integer value) {
            addCriterion("id_persona <=", value, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaIn(List<Integer> values) {
            addCriterion("id_persona in", values, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaNotIn(List<Integer> values) {
            addCriterion("id_persona not in", values, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaBetween(Integer value1, Integer value2) {
            addCriterion("id_persona between", value1, value2, "idPersona");
            return (Criteria) this;
        }

        public Criteria andIdPersonaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_persona not between", value1, value2, "idPersona");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoManoIsNull() {
            addCriterion("codigo_tipo_mano is null");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoManoIsNotNull() {
            addCriterion("codigo_tipo_mano is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoManoEqualTo(String value) {
            addCriterion("codigo_tipo_mano =", value, "codigoTipoMano");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoManoNotEqualTo(String value) {
            addCriterion("codigo_tipo_mano <>", value, "codigoTipoMano");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoManoGreaterThan(String value) {
            addCriterion("codigo_tipo_mano >", value, "codigoTipoMano");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoManoGreaterThanOrEqualTo(String value) {
            addCriterion("codigo_tipo_mano >=", value, "codigoTipoMano");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoManoLessThan(String value) {
            addCriterion("codigo_tipo_mano <", value, "codigoTipoMano");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoManoLessThanOrEqualTo(String value) {
            addCriterion("codigo_tipo_mano <=", value, "codigoTipoMano");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoManoLike(String value) {
            addCriterion("codigo_tipo_mano like", value, "codigoTipoMano");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoManoNotLike(String value) {
            addCriterion("codigo_tipo_mano not like", value, "codigoTipoMano");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoManoIn(List<String> values) {
            addCriterion("codigo_tipo_mano in", values, "codigoTipoMano");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoManoNotIn(List<String> values) {
            addCriterion("codigo_tipo_mano not in", values, "codigoTipoMano");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoManoBetween(String value1, String value2) {
            addCriterion("codigo_tipo_mano between", value1, value2, "codigoTipoMano");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoManoNotBetween(String value1, String value2) {
            addCriterion("codigo_tipo_mano not between", value1, value2, "codigoTipoMano");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoDedoIsNull() {
            addCriterion("codigo_tipo_dedo is null");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoDedoIsNotNull() {
            addCriterion("codigo_tipo_dedo is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoDedoEqualTo(String value) {
            addCriterion("codigo_tipo_dedo =", value, "codigoTipoDedo");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoDedoNotEqualTo(String value) {
            addCriterion("codigo_tipo_dedo <>", value, "codigoTipoDedo");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoDedoGreaterThan(String value) {
            addCriterion("codigo_tipo_dedo >", value, "codigoTipoDedo");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoDedoGreaterThanOrEqualTo(String value) {
            addCriterion("codigo_tipo_dedo >=", value, "codigoTipoDedo");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoDedoLessThan(String value) {
            addCriterion("codigo_tipo_dedo <", value, "codigoTipoDedo");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoDedoLessThanOrEqualTo(String value) {
            addCriterion("codigo_tipo_dedo <=", value, "codigoTipoDedo");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoDedoLike(String value) {
            addCriterion("codigo_tipo_dedo like", value, "codigoTipoDedo");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoDedoNotLike(String value) {
            addCriterion("codigo_tipo_dedo not like", value, "codigoTipoDedo");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoDedoIn(List<String> values) {
            addCriterion("codigo_tipo_dedo in", values, "codigoTipoDedo");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoDedoNotIn(List<String> values) {
            addCriterion("codigo_tipo_dedo not in", values, "codigoTipoDedo");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoDedoBetween(String value1, String value2) {
            addCriterion("codigo_tipo_dedo between", value1, value2, "codigoTipoDedo");
            return (Criteria) this;
        }

        public Criteria andCodigoTipoDedoNotBetween(String value1, String value2) {
            addCriterion("codigo_tipo_dedo not between", value1, value2, "codigoTipoDedo");
            return (Criteria) this;
        }

        public Criteria andObservacionIsNull() {
            addCriterion("observacion is null");
            return (Criteria) this;
        }

        public Criteria andObservacionIsNotNull() {
            addCriterion("observacion is not null");
            return (Criteria) this;
        }

        public Criteria andObservacionEqualTo(String value) {
            addCriterion("observacion =", value, "observacion");
            return (Criteria) this;
        }

        public Criteria andObservacionNotEqualTo(String value) {
            addCriterion("observacion <>", value, "observacion");
            return (Criteria) this;
        }

        public Criteria andObservacionGreaterThan(String value) {
            addCriterion("observacion >", value, "observacion");
            return (Criteria) this;
        }

        public Criteria andObservacionGreaterThanOrEqualTo(String value) {
            addCriterion("observacion >=", value, "observacion");
            return (Criteria) this;
        }

        public Criteria andObservacionLessThan(String value) {
            addCriterion("observacion <", value, "observacion");
            return (Criteria) this;
        }

        public Criteria andObservacionLessThanOrEqualTo(String value) {
            addCriterion("observacion <=", value, "observacion");
            return (Criteria) this;
        }

        public Criteria andObservacionLike(String value) {
            addCriterion("observacion like", value, "observacion");
            return (Criteria) this;
        }

        public Criteria andObservacionNotLike(String value) {
            addCriterion("observacion not like", value, "observacion");
            return (Criteria) this;
        }

        public Criteria andObservacionIn(List<String> values) {
            addCriterion("observacion in", values, "observacion");
            return (Criteria) this;
        }

        public Criteria andObservacionNotIn(List<String> values) {
            addCriterion("observacion not in", values, "observacion");
            return (Criteria) this;
        }

        public Criteria andObservacionBetween(String value1, String value2) {
            addCriterion("observacion between", value1, value2, "observacion");
            return (Criteria) this;
        }

        public Criteria andObservacionNotBetween(String value1, String value2) {
            addCriterion("observacion not between", value1, value2, "observacion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 03 02:37:34 BOT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table personas_huellas_digitales
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}