package org.quarkbit.controlpalabravida.dao.domain;

public class PersonaHuellaDigital implements Comparable<PersonaHuellaDigital> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_huellas_digitales.id_huella
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Integer idHuella;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_huellas_digitales.id_persona
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Integer idPersona;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_huellas_digitales.codigo_tipo_mano
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String codigoTipoMano;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_huellas_digitales.codigo_tipo_dedo
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String codigoTipoDedo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_huellas_digitales.observacion
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String observacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_huellas_digitales.huella_digital
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private byte[] huellaDigital;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_huellas_digitales.id_huella
     *
     * @return the value of personas_huellas_digitales.id_huella
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Integer getIdHuella() {
        return idHuella;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_huellas_digitales.id_huella
     *
     * @param idHuella the value for personas_huellas_digitales.id_huella
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setIdHuella(Integer idHuella) {
        this.idHuella = idHuella;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_huellas_digitales.id_persona
     *
     * @return the value of personas_huellas_digitales.id_persona
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Integer getIdPersona() {
        return idPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_huellas_digitales.id_persona
     *
     * @param idPersona the value for personas_huellas_digitales.id_persona
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_huellas_digitales.codigo_tipo_mano
     *
     * @return the value of personas_huellas_digitales.codigo_tipo_mano
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getCodigoTipoMano() {
        return codigoTipoMano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_huellas_digitales.codigo_tipo_mano
     *
     * @param codigoTipoMano the value for personas_huellas_digitales.codigo_tipo_mano
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setCodigoTipoMano(String codigoTipoMano) {
        this.codigoTipoMano = codigoTipoMano == null ? null : codigoTipoMano.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_huellas_digitales.codigo_tipo_dedo
     *
     * @return the value of personas_huellas_digitales.codigo_tipo_dedo
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getCodigoTipoDedo() {
        return codigoTipoDedo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_huellas_digitales.codigo_tipo_dedo
     *
     * @param codigoTipoDedo the value for personas_huellas_digitales.codigo_tipo_dedo
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setCodigoTipoDedo(String codigoTipoDedo) {
        this.codigoTipoDedo = codigoTipoDedo == null ? null : codigoTipoDedo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_huellas_digitales.observacion
     *
     * @return the value of personas_huellas_digitales.observacion
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getObservacion() {
        return observacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_huellas_digitales.observacion
     *
     * @param observacion the value for personas_huellas_digitales.observacion
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setObservacion(String observacion) {
        this.observacion = observacion == null ? null : observacion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_huellas_digitales.huella_digital
     *
     * @return the value of personas_huellas_digitales.huella_digital
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public byte[] getHuellaDigital() {
        return huellaDigital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_huellas_digitales.huella_digital
     *
     * @param huellaDigital the value for personas_huellas_digitales.huella_digital
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setHuellaDigital(byte[] huellaDigital) {
        this.huellaDigital = huellaDigital;
    }
    
    public String obtenerDedo()
    {
    	if(codigoTipoMano != null && codigoTipoMano.length() > 0)
    	{
	    	switch (codigoTipoMano.charAt(0)) {
			case 'P':
				return "PULGAR";
			case 'I':
				return "INDICE";
			case 'C':
				return "CENTRO";
			case 'A':
				return "ANULAR";
			case 'M':
				return "ME\u00D1IQUE";
			default:
				break;
			}
    	}
    	return "";
    }
    public void enviarDedo(String mano)
    {
    	
    	if(mano.compareTo("PULGAR") == 0)
    	{
    		this.codigoTipoMano = "P";
    	}
    	if(mano.compareTo("INDICE") == 0)
    	{
    		this.codigoTipoMano = "I";
    	}
    	if(mano.compareTo("CENTRO") == 0)
    	{
    		this.codigoTipoMano = "C";
    	}
    	if(mano.compareTo("ANULAR") == 0)
    	{
    		this.codigoTipoMano = "A";
    	}
    	if(mano.compareTo("ME\u00D1IQUE") == 0)
    	{
    		this.codigoTipoMano = "M";
    	}
    }
    
    public String obtenerMano()
    {
    	if(codigoTipoDedo != null && codigoTipoDedo.length() > 0)
    	{
	    	switch (codigoTipoDedo.charAt(0)) {
			case 'I':
				return "IZQUIERDA";
			case 'D':
				return "DERECHA";
	
			default:
				return "";
			}
    	}
    	return "";
    }
    public void enviarMano(String dedo)
    {
    	if(dedo.compareTo("IZQUIERDA") == 0)
    	{
    		this.codigoTipoDedo = "I";
    	}
    	if(dedo.compareTo("DERECHA") == 0)
    	{
    		this.codigoTipoDedo = "D";
    	}
    }

	@Override
	public int compareTo(PersonaHuellaDigital o) {
		// TODO Auto-generated method stub
		return (( this.idHuella > o.idHuella ? 1 : (this.idHuella < o.idHuella ? -1 : 0 ) )) ;
	}

}