package org.quarkbit.controlpalabravida.dao.domain;

import java.util.Date;

public class PersonaEventoAsistencia {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_asistencia.id_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Integer idAsistencia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_asistencia.id_evento
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Integer idEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_asistencia.id_persona
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Integer idPersona;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_asistencia.fecha_registro
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Date fechaRegistro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_asistencia.hora_registro
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Date horaRegistro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_asistencia.tipo_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String tipoAsistencia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_asistencia.tipo_ingreso
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String tipoIngreso;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_asistencia.id_asistencia
     *
     * @return the value of personas_eventos_asistencia.id_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Integer getIdAsistencia() {
        return idAsistencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_asistencia.id_asistencia
     *
     * @param idAsistencia the value for personas_eventos_asistencia.id_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setIdAsistencia(Integer idAsistencia) {
        this.idAsistencia = idAsistencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_asistencia.id_evento
     *
     * @return the value of personas_eventos_asistencia.id_evento
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Integer getIdEvento() {
        return idEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_asistencia.id_evento
     *
     * @param idEvento the value for personas_eventos_asistencia.id_evento
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setIdEvento(Integer idEvento) {
        this.idEvento = idEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_asistencia.id_persona
     *
     * @return the value of personas_eventos_asistencia.id_persona
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Integer getIdPersona() {
        return idPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_asistencia.id_persona
     *
     * @param idPersona the value for personas_eventos_asistencia.id_persona
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_asistencia.fecha_registro
     *
     * @return the value of personas_eventos_asistencia.fecha_registro
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_asistencia.fecha_registro
     *
     * @param fechaRegistro the value for personas_eventos_asistencia.fecha_registro
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_asistencia.hora_registro
     *
     * @return the value of personas_eventos_asistencia.hora_registro
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Date getHoraRegistro() {
        return horaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_asistencia.hora_registro
     *
     * @param horaRegistro the value for personas_eventos_asistencia.hora_registro
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setHoraRegistro(Date horaRegistro) {
        this.horaRegistro = horaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_asistencia.tipo_asistencia
     *
     * @return the value of personas_eventos_asistencia.tipo_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getTipoAsistencia() {
        return tipoAsistencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_asistencia.tipo_asistencia
     *
     * @param tipoAsistencia the value for personas_eventos_asistencia.tipo_asistencia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setTipoAsistencia(String tipoAsistencia) {
        this.tipoAsistencia = tipoAsistencia == null ? null : tipoAsistencia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_asistencia.tipo_ingreso
     *
     * @return the value of personas_eventos_asistencia.tipo_ingreso
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getTipoIngreso() {
        return tipoIngreso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_asistencia.tipo_ingreso
     *
     * @param tipoIngreso the value for personas_eventos_asistencia.tipo_ingreso
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setTipoIngreso(String tipoIngreso) {
        this.tipoIngreso = tipoIngreso == null ? null : tipoIngreso.trim();
    }
}