package org.quarkbit.controlpalabravida.dao.domain;

import java.util.Date;

public class PersonaEventoPermisos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_permisos.id_permiso
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    private Integer id_permiso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_permisos.id_evento
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    private Integer id_evento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_permisos.id_persona
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    private Integer id_persona;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_permisos.id_usuario
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    private Integer id_usuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_permisos.fecha_registro
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    private Date fecha_registro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_permisos.fecha_permiso
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    private Date fecha_permiso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_permisos.fecha_fin_permiso
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    private Date fechaFinPermiso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_permisos.tipo_permiso
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    private String tipo_permiso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas_eventos_permisos.motivo
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    private String motivo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_permisos.id_permiso
     *
     * @return the value of personas_eventos_permisos.id_permiso
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public Integer getId_permiso() {
        return id_permiso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_permisos.id_permiso
     *
     * @param id_permiso the value for personas_eventos_permisos.id_permiso
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public void setId_permiso(Integer id_permiso) {
        this.id_permiso = id_permiso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_permisos.id_evento
     *
     * @return the value of personas_eventos_permisos.id_evento
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public Integer getId_evento() {
        return id_evento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_permisos.id_evento
     *
     * @param id_evento the value for personas_eventos_permisos.id_evento
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public void setId_evento(Integer id_evento) {
        this.id_evento = id_evento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_permisos.id_persona
     *
     * @return the value of personas_eventos_permisos.id_persona
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public Integer getId_persona() {
        return id_persona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_permisos.id_persona
     *
     * @param id_persona the value for personas_eventos_permisos.id_persona
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public void setId_persona(Integer id_persona) {
        this.id_persona = id_persona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_permisos.id_usuario
     *
     * @return the value of personas_eventos_permisos.id_usuario
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public Integer getId_usuario() {
        return id_usuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_permisos.id_usuario
     *
     * @param id_usuario the value for personas_eventos_permisos.id_usuario
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public void setId_usuario(Integer id_usuario) {
        this.id_usuario = id_usuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_permisos.fecha_registro
     *
     * @return the value of personas_eventos_permisos.fecha_registro
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public Date getFecha_registro() {
        return fecha_registro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_permisos.fecha_registro
     *
     * @param fecha_registro the value for personas_eventos_permisos.fecha_registro
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public void setFecha_registro(Date fecha_registro) {
        this.fecha_registro = fecha_registro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_permisos.fecha_permiso
     *
     * @return the value of personas_eventos_permisos.fecha_permiso
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public Date getFecha_permiso() {
        return fecha_permiso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_permisos.fecha_permiso
     *
     * @param fecha_permiso the value for personas_eventos_permisos.fecha_permiso
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public void setFecha_permiso(Date fecha_permiso) {
        this.fecha_permiso = fecha_permiso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_permisos.fecha_fin_permiso
     *
     * @return the value of personas_eventos_permisos.fecha_fin_permiso
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public Date getFechaFinPermiso() {
        return fechaFinPermiso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_permisos.fecha_fin_permiso
     *
     * @param fechaFinPermiso the value for personas_eventos_permisos.fecha_fin_permiso
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public void setFechaFinPermiso(Date fechaFinPermiso) {
        this.fechaFinPermiso = fechaFinPermiso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_permisos.tipo_permiso
     *
     * @return the value of personas_eventos_permisos.tipo_permiso
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public String getTipo_permiso() {
        return tipo_permiso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_permisos.tipo_permiso
     *
     * @param tipo_permiso the value for personas_eventos_permisos.tipo_permiso
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public void setTipo_permiso(String tipo_permiso) {
        this.tipo_permiso = tipo_permiso == null ? null : tipo_permiso.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas_eventos_permisos.motivo
     *
     * @return the value of personas_eventos_permisos.motivo
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public String getMotivo() {
        return motivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas_eventos_permisos.motivo
     *
     * @param motivo the value for personas_eventos_permisos.motivo
     *
     * @mbggenerated Mon Jun 13 11:29:50 BOT 2016
     */
    public void setMotivo(String motivo) {
        this.motivo = motivo == null ? null : motivo.trim();
    }
}