package org.quarkbit.controlpalabravida.dao.domain;

import java.util.Date;

public class Persona implements Comparable<Persona> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas.id_persona
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Integer idPersona;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas.ci
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String ci;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas.nombres
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String nombres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas.apellidos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String apellidos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas.sexo
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String sexo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas.celular
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String celular;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas.fecha_nacimiento
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Date fechaNacimiento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas.tipo_persona
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String tipoPersona;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personas.ruta_fotografia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String rutaFotografia;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas.id_persona
     *
     * @return the value of personas.id_persona
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Integer getIdPersona() {
        return idPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas.id_persona
     *
     * @param idPersona the value for personas.id_persona
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas.ci
     *
     * @return the value of personas.ci
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getCi() {
        return ci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas.ci
     *
     * @param ci the value for personas.ci
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setCi(String ci) {
        this.ci = ci == null ? null : ci.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas.nombres
     *
     * @return the value of personas.nombres
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getNombres() {
        return nombres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas.nombres
     *
     * @param nombres the value for personas.nombres
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setNombres(String nombres) {
        this.nombres = nombres == null ? null : nombres.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas.apellidos
     *
     * @return the value of personas.apellidos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getApellidos() {
        return apellidos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas.apellidos
     *
     * @param apellidos the value for personas.apellidos
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos == null ? null : apellidos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas.sexo
     *
     * @return the value of personas.sexo
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getSexo() {
        return sexo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas.sexo
     *
     * @param sexo the value for personas.sexo
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setSexo(String sexo) {
        this.sexo = sexo == null ? null : sexo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas.celular
     *
     * @return the value of personas.celular
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getCelular() {
        return celular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas.celular
     *
     * @param celular the value for personas.celular
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setCelular(String celular) {
        this.celular = celular == null ? null : celular.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas.fecha_nacimiento
     *
     * @return the value of personas.fecha_nacimiento
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Date getFechaNacimiento() {
        return fechaNacimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas.fecha_nacimiento
     *
     * @param fechaNacimiento the value for personas.fecha_nacimiento
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas.tipo_persona
     *
     * @return the value of personas.tipo_persona
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getTipoPersona() {
        return tipoPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas.tipo_persona
     *
     * @param tipoPersona the value for personas.tipo_persona
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setTipoPersona(String tipoPersona) {
        this.tipoPersona = tipoPersona == null ? null : tipoPersona.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personas.ruta_fotografia
     *
     * @return the value of personas.ruta_fotografia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getRutaFotografia() {
        return rutaFotografia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personas.ruta_fotografia
     *
     * @param rutaFotografia the value for personas.ruta_fotografia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setRutaFotografia(String rutaFotografia) {
        this.rutaFotografia = rutaFotografia == null ? null : rutaFotografia.trim();
    }
    
    public String getNombreCompleto()
    {
    	return nombres + " " + apellidos;
    }

	@Override
	public int compareTo(Persona o) {
		// TODO Auto-generated method stub
		return this.getNombreCompleto().compareTo(o.getNombreCompleto());
	}
	
	public String obtenerSexo()
	{	
		if(this.sexo.compareTo("M") == 0)
			return "MASCULINO";
		else
			return "FEMENINO";
	}
	
	public void enviarSexo(String sexo)
	{
		if(sexo.compareTo("MASCULINO") == 0)
			this.sexo = "M";
		else
			this.sexo = "F";
			
	}
}