package org.quarkbit.controlpalabravida.dao.domain;

import java.util.Date;

public class Usuario {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.id_usuario
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Integer idUsuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.fecha_registro
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private Date fechaRegistro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.nombre_usuario
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String nombreUsuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.contrasenia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    private String contrasenia;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.id_usuario
     *
     * @return the value of usuarios.id_usuario
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.id_usuario
     *
     * @param idUsuario the value for usuarios.id_usuario
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.fecha_registro
     *
     * @return the value of usuarios.fecha_registro
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.fecha_registro
     *
     * @param fechaRegistro the value for usuarios.fecha_registro
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.nombre_usuario
     *
     * @return the value of usuarios.nombre_usuario
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getNombreUsuario() {
        return nombreUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.nombre_usuario
     *
     * @param nombreUsuario the value for usuarios.nombre_usuario
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario == null ? null : nombreUsuario.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.contrasenia
     *
     * @return the value of usuarios.contrasenia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public String getContrasenia() {
        return contrasenia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.contrasenia
     *
     * @param contrasenia the value for usuarios.contrasenia
     *
     * @mbggenerated Fri Jun 03 02:37:34 BOT 2016
     */
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia == null ? null : contrasenia.trim();
    }
}